steps:
  - name: node:$_NODE_VERSION
    entrypoint: npm
    args:
      - 'install'
  - name: node:$_NODE_VERSION
    env:
      - 'GITHUB_TOKEN=$_GH_TOKEN'
      - 'NPM_TOKEN=$_NPM_TOKEN'
    entrypoint: npm
    args:
      - 'run'
      - 'semantic-release'
      - '--'
      - '--no-ci'