---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: semantic-release-test
  namespace: staging
  labels:
    app: semantic-release-test
  annotations:
    # keel 설정. dev- 로 시작하는 tag 를 갖는 이미지일떄만 동작합니다.
    # 이 tag 는 annotations 에 있어도 동작합니다.
    keel.sh/policy: "glob:release-*"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: semantic-release-test
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: semantic-release-test
    spec:
      volumes:
        - name: google-cloud-key
          secret:
            defaultMode: 420
            secretName: rec-spot-receiver-key
      containers:
        - name: semantic-release-test
          image: "gcr.io/sc-data-mart/semantic-release-test"
          resources:
            limits:
              cpu: 300m
              memory: 500Mi
            requests:
              cpu: 200m
              memory: 300Mi
          readinessProbe:
            httpGet:
              path: /
              port: 3000
          imagePullPolicy: Always
          volumeMounts:
            - name: google-cloud-key
              mountPath: /var/secrets/google

---
# server ClusterIP
apiVersion: v1
kind: Service
metadata:
  name: semantic-release-test-clusterip
  namespace: staging
  labels:
    app: semantic-release-test
spec:
  type: ClusterIP
  sessionAffinity: None
  selector:
    app: semantic-release-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
  labels:
    app: semantic-release-test
  name: semantic-release-test-ingress
  namespace: staging